import type { ResumeDesignSettings, ResumeContent } from "./types";

export const DEFAULT_DESIGN: ResumeDesignSettings = {
  template: "classic",
  font: "clean",
  accentColor: "#0D9488",
  lineSpacing: 1.4,
  headerAlignment: "left",
  dateFormat: "short",
  bodySize: "M",
  nameSize: "M",
  bulletStyle: "dot",
  paperSize: "a4",
  sectionOrder: [
    "contact",
    "targetTitle",
    "summary",
    "experience",
    "education",
    "skills",
    "certifications",
    "awards",
    "projects",
    "volunteering",
    "publications",
  ],
  sectionSpacing: 16,
  marginX: 0.75,
  marginY: 0.5,
  pageBreaks: [],
  nameWeight: "bold",
  sectionHeadingSize: "M",
  sectionHeadingWeight: "bold",
  sectionHeadingCase: "uppercase",
  contactSeparator: "pipe",
  sidebarSections: ["contact", "targetTitle", "skills", "education", "certifications"],
};

export const DEFAULT_CONTENT: ResumeContent = {
  sections: {
    contact: true,
    targetTitle: true,
    summary: true,
    experience: true,
    education: true,
    skills: true,
    certifications: true,
    awards: false,
    projects: false,
    volunteering: false,
    publications: false,
  },
  contact: { name: "", email: "", phone: "", location: "", linkedin: "", website: "" },
  targetTitle: { title: "" },
  summary: { content: "" },
  experience: { items: [] },
  education: { items: [] },
  skills: { categories: [] },
  certifications: { items: [] },
  awards: { items: [] },
  projects: { items: [] },
  volunteering: { items: [] },
  publications: { items: [] },
};
