import type { TemplateName } from "./types";
import { TEMPLATE_LABELS } from "./template-labels";

/**
 * Template thumbnails: one Letter-size JPEG per template, generated by
 * `scripts/generate-template-thumbnails.ts` from the sample personas in
 * lib/resume/sample-personas.ts. Every surface that shows a template preview
 * (marketing pages, the editor picker, the designer panel) reads its path and
 * alt text from here so filenames and SEO copy live in one place.
 */

/** Letter (8.5 × 11 in) at 150 DPI. */
export const THUMBNAIL_WIDTH = 1275;
export const THUMBNAIL_HEIGHT = 1650;

/** Templates whose layout renders a headshot (avatarMode "photo"). */
export const PHOTO_TEMPLATES: ReadonlySet<TemplateName> = new Set<TemplateName>([
  "aurora",
  "blueprint",
  "bold-accent",
  "clean-sidebar",
  "coastal",
  "electric-lilac",
  "executive-pro",
  "executive-sidebar",
  "meridian",
  "orchid",
  "portrait",
  "wentworth",
]);

/**
 * Alt text describes what the image shows (layout + the sample candidate) and
 * carries the search phrase naturally. Harvard is the site's strongest page,
 * so its alt names the format the way people search for it.
 */
const ALT: Record<TemplateName, string> = {
  classic: "Classic resume template, a clean single-column ATS-friendly format, shown with a sample VP of Engineering resume",
  "classic-serif": "Classic Serif resume template with serif type and grey section bands, shown with a sample registered nurse resume",
  sharp: "Sharp resume template with bold headings and section rules, shown with a sample cloud engineer resume",
  minimal: "Minimal resume template, a simple one-page format, shown with a sample entry-level business analyst resume",
  executive: "Executive resume template for senior roles, shown with a sample regional sales director resume",
  "executive-pro": "Executive Pro resume template with photo header and dark contact bar, shown with a sample management consultant resume",
  sidebar: "Slate resume template with a dark left sidebar, shown with a sample product designer resume",
  "sidebar-right": "Onyx resume template with a right sidebar for skills and education, shown with a sample data scientist resume",
  "two-column": "Horizon two-column resume template with a full-width header, shown with a sample software engineer resume",
  divide: "Divide two-column resume template with a vertical divider, shown with a sample marketing director resume",
  folio: "Folio resume template with a colored sidebar, shown with a sample brand designer resume",
  metro: "Metro resume template, shown with a sample senior product manager resume",
  harvard:
    "Harvard resume template: one-page, ATS-friendly Harvard format with education and experience sections, shown with a sample consultant resume",
  ledger: "Ledger resume template for finance and accounting, shown with a sample CPA resume",
  aurora: "Aurora two-column resume template with photo and skill chips, shown with a sample product designer resume",
  "electric-lilac": "Electric Lilac resume template with a bold color sidebar and photo, shown with a sample brand designer resume",
  "bold-accent": "Bold Accent resume template with photo and accent section icons, shown with a sample marketing director resume",
  "executive-sidebar": "Executive Sidebar resume template with photo in a dark sidebar, shown with a sample customer success leader resume",
  "clean-sidebar": "Clean Sidebar resume template with photo and a warm sidebar, shown with a sample growth marketing resume",
  blueprint: "Blueprint two-column resume template with photo and editorial header, shown with a sample brand designer resume",
  wentworth: "Wentworth minimal resume template with circular photo, shown with a sample head of customer success resume",
  orchid: "Orchid resume template with photo, serif headings and a warm sidebar, shown with a sample registered nurse resume",
  coastal: "Coastal resume template with photo and teal header, shown with a sample sales director resume",
  portrait: "Portrait resume template with headshot and split-weight name, shown with a sample growth marketing resume",
  regent: "Regent resume template with a centered serif header, shown with a sample VP of Engineering resume",
  meridian: "Meridian two-column resume template with photo and icon headings, shown with a sample cloud engineer resume",
  vantage: "Vantage resume template with company and school logos, shown with a sample senior product manager resume",
  linen: "Linen minimalist two-column resume template, shown with a sample management consultant resume",
  graphite: "Graphite resume template with pill section headings, shown with a sample entry-level business analyst resume",
  sterling: "Sterling ATS-friendly resume template with a skills table, shown with a sample CPA resume",
  ember: "Ember ATS-friendly two-column resume template with a contact and skills rail, shown with a sample software engineer resume",
  canopy: "Canopy resume template with a sage header band, shown with a sample data scientist resume",
};

function fileName(template: TemplateName): string {
  return `${TEMPLATE_LABELS[template].toLowerCase().replace(/[^a-z0-9]+/g, "-")}-resume-template.jpg`;
}

export interface TemplateThumbnail {
  src: string;
  alt: string;
  /** "<Name> resume template", for title attributes and image captions. */
  title: string;
  width: number;
  height: number;
}

export function templateThumbnail(template: TemplateName): TemplateThumbnail {
  return {
    src: `/img/templates/${fileName(template)}`,
    alt: ALT[template],
    title: `${TEMPLATE_LABELS[template]} resume template`,
    width: THUMBNAIL_WIDTH,
    height: THUMBNAIL_HEIGHT,
  };
}

/** Published filename (no directory) for a template's thumbnail. */
export function thumbnailFileName(template: TemplateName): string {
  return fileName(template);
}
