import type { TemplateName } from "./types";

/** Display names for every template slug shipped in code. */
export const TEMPLATE_LABELS: Record<TemplateName, string> = {
  classic: "Classic",
  "classic-serif": "Classic Serif",
  sharp: "Sharp",
  minimal: "Minimal",
  executive: "Executive",
  "executive-pro": "Executive Pro",
  sidebar: "Slate",
  "sidebar-right": "Onyx",
  "two-column": "Horizon",
  divide: "Divide",
  folio: "Folio",
  metro: "Metro",
  harvard: "Harvard",
  ledger: "Ledger",
  aurora: "Aurora",
  "electric-lilac": "Electric Lilac",
  "bold-accent": "Bold Accent",
  "executive-sidebar": "Executive Sidebar",
  "clean-sidebar": "Clean Sidebar",
  blueprint: "Blueprint",
  wentworth: "Wentworth",
  orchid: "Orchid",
  coastal: "Coastal",
  portrait: "Portrait",
  regent: "Regent",
  meridian: "Meridian",
  vantage: "Vantage",
  linen: "Linen",
  graphite: "Graphite",
  sterling: "Sterling",
  ember: "Ember",
  canopy: "Canopy",
};
