/** Worldwide country dial codes (ITU E.164), alphabetical. The program is open to all locations. */
export const COUNTRY_CODES = [
  { iso: "AF", label: "Afghanistan", dial: "+93" },
  { iso: "AL", label: "Albania", dial: "+355" },
  { iso: "DZ", label: "Algeria", dial: "+213" },
  { iso: "AD", label: "Andorra", dial: "+376" },
  { iso: "AO", label: "Angola", dial: "+244" },
  { iso: "AG", label: "Antigua and Barbuda", dial: "+1" },
  { iso: "AR", label: "Argentina", dial: "+54" },
  { iso: "AM", label: "Armenia", dial: "+374" },
  { iso: "AU", label: "Australia", dial: "+61" },
  { iso: "AT", label: "Austria", dial: "+43" },
  { iso: "AZ", label: "Azerbaijan", dial: "+994" },
  { iso: "BS", label: "Bahamas", dial: "+1" },
  { iso: "BH", label: "Bahrain", dial: "+973" },
  { iso: "BD", label: "Bangladesh", dial: "+880" },
  { iso: "BB", label: "Barbados", dial: "+1" },
  { iso: "BY", label: "Belarus", dial: "+375" },
  { iso: "BE", label: "Belgium", dial: "+32" },
  { iso: "BZ", label: "Belize", dial: "+501" },
  { iso: "BJ", label: "Benin", dial: "+229" },
  { iso: "BT", label: "Bhutan", dial: "+975" },
  { iso: "BO", label: "Bolivia", dial: "+591" },
  { iso: "BA", label: "Bosnia and Herzegovina", dial: "+387" },
  { iso: "BW", label: "Botswana", dial: "+267" },
  { iso: "BR", label: "Brazil", dial: "+55" },
  { iso: "BN", label: "Brunei", dial: "+673" },
  { iso: "BG", label: "Bulgaria", dial: "+359" },
  { iso: "BF", label: "Burkina Faso", dial: "+226" },
  { iso: "BI", label: "Burundi", dial: "+257" },
  { iso: "KH", label: "Cambodia", dial: "+855" },
  { iso: "CM", label: "Cameroon", dial: "+237" },
  { iso: "CA", label: "Canada", dial: "+1" },
  { iso: "CV", label: "Cape Verde", dial: "+238" },
  { iso: "CF", label: "Central African Republic", dial: "+236" },
  { iso: "TD", label: "Chad", dial: "+235" },
  { iso: "CL", label: "Chile", dial: "+56" },
  { iso: "CN", label: "China", dial: "+86" },
  { iso: "CO", label: "Colombia", dial: "+57" },
  { iso: "KM", label: "Comoros", dial: "+269" },
  { iso: "CG", label: "Congo", dial: "+242" },
  { iso: "CD", label: "Congo (DRC)", dial: "+243" },
  { iso: "CR", label: "Costa Rica", dial: "+506" },
  { iso: "CI", label: "Côte d'Ivoire", dial: "+225" },
  { iso: "HR", label: "Croatia", dial: "+385" },
  { iso: "CU", label: "Cuba", dial: "+53" },
  { iso: "CY", label: "Cyprus", dial: "+357" },
  { iso: "CZ", label: "Czechia", dial: "+420" },
  { iso: "DK", label: "Denmark", dial: "+45" },
  { iso: "DJ", label: "Djibouti", dial: "+253" },
  { iso: "DM", label: "Dominica", dial: "+1" },
  { iso: "DO", label: "Dominican Republic", dial: "+1" },
  { iso: "EC", label: "Ecuador", dial: "+593" },
  { iso: "EG", label: "Egypt", dial: "+20" },
  { iso: "SV", label: "El Salvador", dial: "+503" },
  { iso: "GQ", label: "Equatorial Guinea", dial: "+240" },
  { iso: "ER", label: "Eritrea", dial: "+291" },
  { iso: "EE", label: "Estonia", dial: "+372" },
  { iso: "SZ", label: "Eswatini", dial: "+268" },
  { iso: "ET", label: "Ethiopia", dial: "+251" },
  { iso: "FJ", label: "Fiji", dial: "+679" },
  { iso: "FI", label: "Finland", dial: "+358" },
  { iso: "FR", label: "France", dial: "+33" },
  { iso: "GA", label: "Gabon", dial: "+241" },
  { iso: "GM", label: "Gambia", dial: "+220" },
  { iso: "GE", label: "Georgia", dial: "+995" },
  { iso: "DE", label: "Germany", dial: "+49" },
  { iso: "GH", label: "Ghana", dial: "+233" },
  { iso: "GR", label: "Greece", dial: "+30" },
  { iso: "GD", label: "Grenada", dial: "+1" },
  { iso: "GT", label: "Guatemala", dial: "+502" },
  { iso: "GN", label: "Guinea", dial: "+224" },
  { iso: "GW", label: "Guinea-Bissau", dial: "+245" },
  { iso: "GY", label: "Guyana", dial: "+592" },
  { iso: "HT", label: "Haiti", dial: "+509" },
  { iso: "HN", label: "Honduras", dial: "+504" },
  { iso: "HK", label: "Hong Kong", dial: "+852" },
  { iso: "HU", label: "Hungary", dial: "+36" },
  { iso: "IS", label: "Iceland", dial: "+354" },
  { iso: "IN", label: "India", dial: "+91" },
  { iso: "ID", label: "Indonesia", dial: "+62" },
  { iso: "IR", label: "Iran", dial: "+98" },
  { iso: "IQ", label: "Iraq", dial: "+964" },
  { iso: "IE", label: "Ireland", dial: "+353" },
  { iso: "IL", label: "Israel", dial: "+972" },
  { iso: "IT", label: "Italy", dial: "+39" },
  { iso: "JM", label: "Jamaica", dial: "+1" },
  { iso: "JP", label: "Japan", dial: "+81" },
  { iso: "JO", label: "Jordan", dial: "+962" },
  { iso: "KZ", label: "Kazakhstan", dial: "+7" },
  { iso: "KE", label: "Kenya", dial: "+254" },
  { iso: "KI", label: "Kiribati", dial: "+686" },
  { iso: "KW", label: "Kuwait", dial: "+965" },
  { iso: "KG", label: "Kyrgyzstan", dial: "+996" },
  { iso: "LA", label: "Laos", dial: "+856" },
  { iso: "LV", label: "Latvia", dial: "+371" },
  { iso: "LB", label: "Lebanon", dial: "+961" },
  { iso: "LS", label: "Lesotho", dial: "+266" },
  { iso: "LR", label: "Liberia", dial: "+231" },
  { iso: "LY", label: "Libya", dial: "+218" },
  { iso: "LI", label: "Liechtenstein", dial: "+423" },
  { iso: "LT", label: "Lithuania", dial: "+370" },
  { iso: "LU", label: "Luxembourg", dial: "+352" },
  { iso: "MO", label: "Macao", dial: "+853" },
  { iso: "MG", label: "Madagascar", dial: "+261" },
  { iso: "MW", label: "Malawi", dial: "+265" },
  { iso: "MY", label: "Malaysia", dial: "+60" },
  { iso: "MV", label: "Maldives", dial: "+960" },
  { iso: "ML", label: "Mali", dial: "+223" },
  { iso: "MT", label: "Malta", dial: "+356" },
  { iso: "MH", label: "Marshall Islands", dial: "+692" },
  { iso: "MR", label: "Mauritania", dial: "+222" },
  { iso: "MU", label: "Mauritius", dial: "+230" },
  { iso: "MX", label: "Mexico", dial: "+52" },
  { iso: "FM", label: "Micronesia", dial: "+691" },
  { iso: "MD", label: "Moldova", dial: "+373" },
  { iso: "MC", label: "Monaco", dial: "+377" },
  { iso: "MN", label: "Mongolia", dial: "+976" },
  { iso: "ME", label: "Montenegro", dial: "+382" },
  { iso: "MA", label: "Morocco", dial: "+212" },
  { iso: "MZ", label: "Mozambique", dial: "+258" },
  { iso: "MM", label: "Myanmar", dial: "+95" },
  { iso: "NA", label: "Namibia", dial: "+264" },
  { iso: "NR", label: "Nauru", dial: "+674" },
  { iso: "NP", label: "Nepal", dial: "+977" },
  { iso: "NL", label: "Netherlands", dial: "+31" },
  { iso: "NZ", label: "New Zealand", dial: "+64" },
  { iso: "NI", label: "Nicaragua", dial: "+505" },
  { iso: "NE", label: "Niger", dial: "+227" },
  { iso: "NG", label: "Nigeria", dial: "+234" },
  { iso: "KP", label: "North Korea", dial: "+850" },
  { iso: "MK", label: "North Macedonia", dial: "+389" },
  { iso: "NO", label: "Norway", dial: "+47" },
  { iso: "OM", label: "Oman", dial: "+968" },
  { iso: "PK", label: "Pakistan", dial: "+92" },
  { iso: "PW", label: "Palau", dial: "+680" },
  { iso: "PS", label: "Palestine", dial: "+970" },
  { iso: "PA", label: "Panama", dial: "+507" },
  { iso: "PG", label: "Papua New Guinea", dial: "+675" },
  { iso: "PY", label: "Paraguay", dial: "+595" },
  { iso: "PE", label: "Peru", dial: "+51" },
  { iso: "PH", label: "Philippines", dial: "+63" },
  { iso: "PL", label: "Poland", dial: "+48" },
  { iso: "PT", label: "Portugal", dial: "+351" },
  { iso: "PR", label: "Puerto Rico", dial: "+1" },
  { iso: "QA", label: "Qatar", dial: "+974" },
  { iso: "RO", label: "Romania", dial: "+40" },
  { iso: "RU", label: "Russia", dial: "+7" },
  { iso: "RW", label: "Rwanda", dial: "+250" },
  { iso: "KN", label: "Saint Kitts and Nevis", dial: "+1" },
  { iso: "LC", label: "Saint Lucia", dial: "+1" },
  { iso: "VC", label: "Saint Vincent and the Grenadines", dial: "+1" },
  { iso: "WS", label: "Samoa", dial: "+685" },
  { iso: "SM", label: "San Marino", dial: "+378" },
  { iso: "ST", label: "São Tomé and Príncipe", dial: "+239" },
  { iso: "SA", label: "Saudi Arabia", dial: "+966" },
  { iso: "SN", label: "Senegal", dial: "+221" },
  { iso: "RS", label: "Serbia", dial: "+381" },
  { iso: "SC", label: "Seychelles", dial: "+248" },
  { iso: "SL", label: "Sierra Leone", dial: "+232" },
  { iso: "SG", label: "Singapore", dial: "+65" },
  { iso: "SK", label: "Slovakia", dial: "+421" },
  { iso: "SI", label: "Slovenia", dial: "+386" },
  { iso: "SB", label: "Solomon Islands", dial: "+677" },
  { iso: "SO", label: "Somalia", dial: "+252" },
  { iso: "ZA", label: "South Africa", dial: "+27" },
  { iso: "KR", label: "South Korea", dial: "+82" },
  { iso: "SS", label: "South Sudan", dial: "+211" },
  { iso: "ES", label: "Spain", dial: "+34" },
  { iso: "LK", label: "Sri Lanka", dial: "+94" },
  { iso: "SD", label: "Sudan", dial: "+249" },
  { iso: "SR", label: "Suriname", dial: "+597" },
  { iso: "SE", label: "Sweden", dial: "+46" },
  { iso: "CH", label: "Switzerland", dial: "+41" },
  { iso: "SY", label: "Syria", dial: "+963" },
  { iso: "TW", label: "Taiwan", dial: "+886" },
  { iso: "TJ", label: "Tajikistan", dial: "+992" },
  { iso: "TZ", label: "Tanzania", dial: "+255" },
  { iso: "TH", label: "Thailand", dial: "+66" },
  { iso: "TL", label: "Timor-Leste", dial: "+670" },
  { iso: "TG", label: "Togo", dial: "+228" },
  { iso: "TO", label: "Tonga", dial: "+676" },
  { iso: "TT", label: "Trinidad and Tobago", dial: "+1" },
  { iso: "TN", label: "Tunisia", dial: "+216" },
  { iso: "TR", label: "Türkiye", dial: "+90" },
  { iso: "TM", label: "Turkmenistan", dial: "+993" },
  { iso: "TV", label: "Tuvalu", dial: "+688" },
  { iso: "UG", label: "Uganda", dial: "+256" },
  { iso: "UA", label: "Ukraine", dial: "+380" },
  { iso: "AE", label: "United Arab Emirates", dial: "+971" },
  { iso: "GB", label: "United Kingdom", dial: "+44" },
  { iso: "US", label: "United States", dial: "+1" },
  { iso: "UY", label: "Uruguay", dial: "+598" },
  { iso: "UZ", label: "Uzbekistan", dial: "+998" },
  { iso: "VU", label: "Vanuatu", dial: "+678" },
  { iso: "VE", label: "Venezuela", dial: "+58" },
  { iso: "VN", label: "Vietnam", dial: "+84" },
  { iso: "YE", label: "Yemen", dial: "+967" },
  { iso: "ZM", label: "Zambia", dial: "+260" },
  { iso: "ZW", label: "Zimbabwe", dial: "+263" },
];
